min_version = "2025.9.25"

[settings]
experimental = true

[tools]
python = "3.12"
uv = "latest"
pre-commit = "prefix:4.2"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.install]
alias = "i"
description = "Install project dependencies with UV"
run = "uv sync"

[tasks.install-dev]
alias = "id"
description = "Install with dev dependencies"
run = "uv sync --all-packages --all-extras"

[tasks.pre-commit]
run = "pre-commit run -a"

[tasks.test]
alias = "t"
description = "Run all tests"
run = "uv run --all-packages --all-extras pytest -q"
